### ISSUE TITLE
[FEATURE] Helm override for kube-rbac-proxy image

### ISSUE THREAD

**Issue by twhite0** [istio-ecosystem/sail-operator#336]
### Is this the right place to submit this?

- [X] This is not a question about how to use the sail-operator

### Feature Description

The [operator image](https://github.com/istio-ecosystem/sail-operator/blob/main/chart/templates/deployment.yaml#L82) provides for an override however the [kube-rbac-proxy](https://github.com/istio-ecosystem/sail-operator/blob/main/chart/templates/deployment.yaml#L56) container does not.  For folks like myself working in an environment with proxied image repositories, we need a means of overriding the image with our internal repo path.

Happy to contribute the changes, just following the "Way of Working" guide asking for a discussion up front.

### Additional Information

something like the following values.yaml enhancement.
```yaml
proxy:
   image:  gcr.io/kubebuilder/kube-rbac-proxy:v0.16.0
   imagePullPolicy: Always
```

and enhancement to deployment.yaml
```yaml
containers:
- args:
   name: kube-rbac-proxy
   image: {{ .Values.proxy.image }}
   imagePullPolicy: {{ .values.proxy.imagePullPolicy }}
```
