### ISSUE TITLE
[BUG] RemoteIstio resource can't be created using latest istio version

### ISSUE THREAD

**Issue by fjglira** [istio-ecosystem/sail-operator#343]
### Is this the right place to submit this?

- [X] This is not a question about how to use the sail-operator

### Bug Description

Following the steps to set multicluster Primary Remote configuration, it is not possible to deploy a new `RemoteIstio` resource by setting `spec.version` to `latest`. 

- RemoteIstio resource:
```
kubectl apply  -f - <<EOF
apiVersion: sailoperator.io/v1alpha1
kind: RemoteIstio
metadata:
  name: default
spec:
  version: latest
  namespace: istio-system
  values:
    istiodRemote:
      injectionPath: /inject/cluster/remote/net/network2
    global:
      remotePilotAddress: 172.18.7.110
EOF
```

The current error in the resource is: 

```
# kubectl describe remoteistio default
Name:         default
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  sailoperator.io/v1alpha1
Kind:         RemoteIstio
Metadata:
  Creation Timestamp:  2024-09-18T09:15:49Z
  Generation:          1
  Resource Version:    2805
  UID:                 4ccda607-1694-44e3-807a-2976c1591ae5
Spec:
  Namespace:  istio-system
  Update Strategy:
    Type:  InPlace
  Values:
    Global:
      Remote Pilot Address:  172.18.7.110
    Istiod Remote:
      Injection Path:  /inject/cluster/remote/net/network2
  Version:             latest
Status:
  Conditions:
    Last Transition Time:  2024-09-18T09:15:49Z
    Message:               error reconciling resource: failed to install/update Helm chart "istiod-remote": failed to install helm chart istiod-remote: template: istiod-remote/templates/services.yaml:5:16: executing "istiod-remote/templates/services.yaml" at <.Values.pilot.enabled>: nil pointer evaluating interface {}.enabled
    Reason:                ReconcileError
    Status:                False
    Type:                  Reconciled
    Last Transition Time:  2024-09-18T09:15:49Z
    Message:               MutatingWebhookConfiguration istio-sidecar-injector not found
    Reason:                IstiodNotReady
    Status:                False
    Type:                  Ready
  Observed Generation:     1
  Revisions:
    In Use:  0
    Ready:   0
    Total:   1
  State:     ReconcileError
Events:      <none>
```

### Operator Version

Running from master branch

### Additional Information

The same issue is happening when we try to set version less than 1.23.0, but in this case, I can see that the folder for those versions does not contain the istiod-remote charts:

```
# find . -type d -name "istiod-remote"
./resources/latest/charts/istiod-remote
./resources/v1.23.0/charts/istiod-remote
```
