### ISSUE TITLE
Move IstioCNI.spec.values.cni to IstioCNI.spec.values?

### ISSUE THREAD

**Issue by luksa** [istio-ecosystem/sail-operator#493]
### Is this the right place to submit this?

- [X] This is not a question about how to use the sail-operator

### Bug Description

The CNI values are currently specified in `IstioCNI.spec.values.cni`, which looks odd, since we already know we're configuring CNI values. The same applies to ZTunnel (`ZTunnel.spec.values.ztunnel`).

Should we move the values one level up (to `IstioCNI.spec.values` and `ZTunnel.spec.values`), since it's clear that those values are for CNI/ZTunnel?

For Istio, things are a bit different, since we don't have `Istio.spec.values.istio`, but `Istio.spec.values.pilot` (and others), but it might make sense to move these values up also. In all three cases, the charts already do use this structure.

### Operator Version

0.1.0

**Comment by dgn** [comment]
Yes, I think this is a good idea

**Comment by dgn** [comment]
The only problem here might be `global` values, right? Currently we set them this way (examples only for CNI but apply to ztunnel as well):

```yaml
spec:
  values:
    global:
      a: b
    cni:
      c: d
```

Option 1 would be to add a new field to the spec
```yaml
spec:
  globalValues:
    a: b
  values:
    c: d
```

Option 2 could be to inline the global field:

```yaml
spec:
  values:
    global:
      a: b
    c: d
```
