### ISSUE TITLE
[BUG] Istio revision tag status not working when the injection is enabled on a pod via sidecar.istio.io/inject: 'true'

### ISSUE THREAD

**Issue by FilipB** [istio-ecosystem/sail-operator#551]
### Is this the right place to submit this?

- [X] This is not a question about how to use the sail-operator

### Bug Description

Having following Istio:
```
apiVersion: sailoperator.io/v1alpha1
kind: Istio
metadata:
  name: ossm-3
spec:
  namespace: istio-system
  updateStrategy:
    type: RevisionBased
  version: v1.24.1
```

and following IstioRevisionTag:
```
apiVersion: sailoperator.io/v1alpha1
kind: IstioRevisionTag
metadata:
  name: default
spec:
  targetRef:
    kind: IstioRevision
    name: ossm-3-v1-24-1
```
the `IstioRevisionTag` status shows `NotReferencedByAnything` even if there are pods with a `sidecar.istio.io/inject: 'true'` label and injected proxies.

```
oc get istiorevisiontags
NAME      STATUS                    IN USE   REVISION         AGE
default   NotReferencedByAnything   False    ossm-3-v1-24-1   24m
```

On the other hand, following is shown when you label an empty namespace (so there no proxies running) with `istio-injection=enabled`:
```
oc get istiorevisiontags
NAME      STATUS    IN USE   REVISION         AGE
default   Healthy   True     ossm-3-v1-24-1   24m
```

### Operator Version

0.3.0-nightly-2025-01-08
