### ISSUE TITLE
Docker Hub rate limits causing failures in e2e tests

### ISSUE THREAD

**Issue by sridhargaddam** [istio-ecosystem/sail-operator#564]
### Is this the right place to submit this?

- [x] This is not a question about how to use the sail-operator

### Bug Description

In the Sail Operator e2e test suite, we use [manifests that pull images](https://github.com/istio-ecosystem/sail-operator/blob/4430fb56d2ce23a37568b73b9e94a469b71cebdd/tests/e2e/util/common/e2e_utils.go#L317) like sleep, helloworld, sample, httpbin etc from Docker Hub. Occasionally, test cases fail due to Docker Hub's rate-limiting restrictions, leading to false test failures.

```
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

### Operator Version

latest

**Comment by FilipB** [comment]
Another option is to configure your OCP:
```
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: docker-images-from-gcr
spec:
  imageDigestMirrors:
  - mirrors:
    - mirror.gcr.io
    source: docker.io
    mirrorSourcePolicy: NeverContactSource
---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: docker-images-from-gcr
spec:
  imageTagMirrors:
  - mirrors:
    - mirror.gcr.io
    source: docker.io
    mirrorSourcePolicy: NeverContactSource
```
