### ISSUE TITLE
[BUG] Configuration in ZTunnelConfig is Ignored while deploying ambient

### ISSUE THREAD

**Issue by sridhargaddam** [istio-ecosystem/sail-operator#567]
### Is this the right place to submit this?

- [x] This is not a question about how to use the sail-operator

### Bug Description

In the Sail Operator ZTunnel resource, any configuration specified under [values.ztunnel](https://github.com/istio-ecosystem/sail-operator/blob/91599443b18ab0c65b149a12e3d36318e15b420f/api/v1alpha1/values_types_extra.go#L42) is ignored.

**Steps to Reproduce:**
1. Install the latest version of Sail Operator in a KinD cluster.
2. Create Istio and IstioCNI resources with profile set to "ambient".
3. Apply the following ZTunnel resource:
```
apiVersion: sailoperator.io/v1alpha1
kind: ZTunnel
metadata:
  name: default
spec:
  version: v1.24.2
  namespace: ztunnel
  profile: ambient
  values:
    ztunnel:
      hub: docker.io/istio
      tag: 1.24.1
      variant: debug
```
4. Wait for the ztunnel DaemonSet to be created.
5. Check the ztunnel image.

**Expected Behavior:**
The ztunnel image should be docker.io/istio/ztunnel:v1.24.1-debug

**Actual Behavior:**
The image points to v1.24.2, ignoring the configuration specified in values.ztunnel

### Operator Version

latest
