### ISSUE TITLE
[BUG] CRD validation and duplication on various configuration items

### ISSUE THREAD

**Issue by michaelalang** [istio-ecosystem/sail-operator#665]
### Is this the right place to submit this?

- [x] This is not a question about how to use the sail-operator

### Bug Description

I recently started to lookin into migration to Sail operator and found various duplicated CRD definitions for items like:

```
  values:
    global:
       meshID      <string>
 ---
  values:  
    meshConfig:
      defaultConfig:
        meshId:      <string>
```
without any explanation which one should be used .

Furthermore the Operator doesn't seem to handle misalignment of configuration items in the CR correctly, like
injecting
```
apiVersion: sailoperator.io/v1alpha1
kind: Istio
metadata:
  name: east
spec:
  namespace: istio-system
  updateStrategy:
    inactiveRevisionDeletionGracePeriodSeconds: 30
    type: RevisionBased
  version: v1.24.1
  values:
    global:
      meshID: east
  meshConfig:   # <<< misaligned should be within `values`
    accessLogFormat: json
    defaultConfig:
      meshId: west
```

is not reported but silently ignored.
Can someone explain the duplication and are we going to fix the validation ?

### Operator Version

0.2

**Comment by sridhargaddam** [comment]
With the latest devel image (dtd: 27/Feb/2025 quay.io/sail-dev/sail-operator:1.1-latest) I see that there is an error (as expected) reported when trying to create the following `Istio` CR. 

```
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: east
spec:
  namespace: istio-system                                                                                                                                                                     
  updateStrategy:
    inactiveRevisionDeletionGracePeriodSeconds: 30
    type: RevisionBased
  version: v1.24.2
  values:
    global:
      meshID: east
  meshConfig:   # <<< misaligned should be within `values`
    accessLogFormat: json
    defaultConfig:
      meshId: west
```

Error:
```
$: k apply -f /tmp/istio.yaml 
Error from server (BadRequest): error when creating "/tmp/istio.yaml": Istio in version "v1" cannot be handled as a Istio: strict decoding error: unknown field "spec.meshConfig"
```
