### ISSUE TITLE
[BUG] ZTunnel resource does not propagate logging level to Daemonset

### ISSUE THREAD

**Issue by cam-garrison** [istio-ecosystem/sail-operator#805]
### Is this the right place to submit this?

- [x] This is not a question about how to use the sail-operator

### Bug Description

When trying to change the logging level from `info` to `debug` in the ZTunnel pods, modifying the ZTunnel's `values` does not seem to have an effect on the variable `RUST_LOG` in the daemonset. 

Trying:
```
  values:
    global:
      logging:
        level: debug
    ztunnel:
      env:
        RUST_LOG: debug
      logging:
        level: debug
```
still has no effect on the `RUST_LOG` level within the resulting Daemonset. 

Tested with istio version 1.24-latest.

### Operator Version

1.0
