### ISSUE TITLE
[BUG] Operator does not override manual changes to owned resources

### ISSUE THREAD

**Issue by nrfox** [istio-ecosystem/sail-operator#841]
### Is this the right place to submit this?

- [x] This is not a question about how to use the sail-operator

### Bug Description

I manually edited the istiod deployment's `spec.replicas` field and I was expecting the sail operator to manually override those changes. Instead, the operator reconciled the resource, re-applied the helm chart, but did not override the manual changes. I'm unsure if it's only specific fields like `spec.replicas` and specific resources like the istiod `Deployment`.

Steps to reproduce:
1. Create an Istio resource
    ```
    kubectl create ns istio-system
    kubectl apply -f - <<EOF
    apiVersion: sailoperator.io/v1                                                                                                                                                                                                                                                            
    kind: Istio                                                                                                                                                                                                                                                                               
    metadata:                                                                                                                                                                                                                                                                                 
      name: default
    spec:
      namespace: istio-system
      version: v1.25.2
    EOF
    ```
2. Check the helm chart rev before patching
    ```
    helm ls -n istio-system
    ```
    ```
    > NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION     
    > default-istiod  istio-system    69              2025-05-22 14:52:57.717940456 +0000 UTC deployed        istiod-1.25.2                   1.25.2          
    ```
3. Modify the istiod deployment directly
    ```
    kubectl patch deployments -n istio-system istiod -p '{"spec": {"replicas": 2}}'
    ```
4. Check the number of replicas after patching
    ```
    kubectl get deployments -n istio-system istiod -o jsonpath='{.spec.replicas}'
    ```
5. Check the helm chart rev after patching to ensure that the operator actually reconciled the `Istio` resource (could also check the logs)
    ```
    helm ls -n istio-system                                                                                                                                                                                                                                 
    ```
    ```
    > NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION     
    > default-istiod  istio-system    71              2025-05-22 14:57:28.225239041 +0000 UTC deployed        istiod-1.25.2                   1.25.2     
    ```

### Operator Version

1.25.2

### Link to Gist with Logs

_No response_

### Additional Information

_No response_
